### PR TITLE
Test GitHub hooks

### PR DESCRIPTION
**Pull request by woopsn**
This is to test the github hooks branch

/webpagetest http://alonetone.com

Does it work?

### CODE REVIEW

**Comment by PerfCheck** [comment]
## [http://alonetone.com](http://www.webpagetest.org//result/160412_75_24N2/)

|  | Waterfall | Screen Shot |
| --- | --- | --- |
| First View (4.40s) |  |  |
| Repeat View (2.20s) |  |  |

**Comment by woopsn** [comment]
Comment triggers should work as well

/webpagetest http://alonetone.com/playlists

**Comment by PerfCheck** [comment]
## [http://alonetone.com/playlists](http://www.webpagetest.org//result/160412_RB_24W6/)

|  | Waterfall | Screen Shot |
| --- | --- | --- |
| First View (5.16s) |  |  |
| Repeat View (2.17s) |  |  |

**Comment by woopsn** [comment]
Multiple urls:

/webpagetest http://alonetone.com/ http://alonetone.com/playlists

**Comment by PerfCheck** [comment]
## [http://alonetone.com/](http://www.webpagetest.org//result/160412_R2_24ZK/)

|  | Waterfall | Screen Shot |
| --- | --- | --- |
| First View (4.18s) |  |  |
| Repeat View (1.38s) |  |  |

## [http://alonetone.com/playlists](http://www.webpagetest.org//result/160412_VM_24ZM/)

|  | Waterfall | Screen Shot |
| --- | --- | --- |
| First View (4.53s) |  |  |
| Repeat View (1.91s) |  |  |

**Comment by woopsn** [comment]
webpagetest options

/webpagetest --mobile http://alonetone.com/

**Comment by PerfCheck** [comment]
### [http://alonetone.com/](http://www.webpagetest.org//result/160412_B9_2510/)

|  | Waterfall | Screen Shot |
| --- | --- | --- |
| First View (5.11s) |  |  |
| Repeat View (2.29s) |  |  |

**Comment by sudara** [comment]
## [http://alonetone.com/](http://www.webpagetest.org//result/160412_B9_2510/)

|  | My Favorite Branch | Master | Results |
| --- | --- | --- | --- |
| First View |   **5.11s** |   **5.45s** | :white_check_mark: 1.2x faster than master |
| Repeat View |  **2.29s** |  **2.69s** | :x: 1.2x slower than master |

**Comment by PerfCheck** [comment]
## [http://alonetone.com](http://www.webpagetest.org//result/160423_2K_7GH/)

|  | Waterfall | Screen Shot |
| --- | --- | --- |
| First View (4.11s) |  |  |
| Repeat View (2.38s) |  |  |

**Comment by PerfCheck** [comment]
## [http://alonetone.com](http://www.webpagetest.org//result/160423_X4_7QC/)

|  | Waterfall | Screen Shot |
| --- | --- | --- |
| First View (4.51s) |  |  |
| Repeat View (2.01s) |  |  |

**Pull request merged**
